server:
  port: 9192
  
spring:
  application:
    name: PAYMENT-SERVICE
  banner:
    location: classpath:banner/banner.txt
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
    url: jdbc:p6spy:h2:mem:testdb
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost   